### ISSUE TITLE
Add support for getting user tokens

### ISSUE THREAD

**Issue by alanphung** [jasonpan12/box-jwt-auth#1]
Looks like it can only do the enterprise/service acct token rn

**Comment by jasonpan12** [comment]
On roadmap.

**Comment by jasonpan12** [comment]
fixed in https://github.com/jasonpan12/box-jwt-auth/pull/3 and https://github.com/jasonpan12/box-jwt-auth/pull/2, and i still don't know how to use github to do more than one thing at a time. /shrug

Feature merged to live (and i can say live because i'm a developer now?)
